
package br.gov.saude.servicos.cnes.v1r0.cnesservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CnesService", targetNamespace = "http://servicos.saude.gov.br/cnes/v1r0/cnesservice", wsdlLocation = "https://servicos.saude.gov.br/cnes/CnesService/v1r0?wsdl")
public class CnesService
    extends Service
{

    private final static URL CNESSERVICE_WSDL_LOCATION;
    private final static WebServiceException CNESSERVICE_EXCEPTION;
    private final static QName CNESSERVICE_QNAME = new QName("http://servicos.saude.gov.br/cnes/v1r0/cnesservice", "CnesService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://servicos.saude.gov.br/cnes/CnesService/v1r0?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CNESSERVICE_WSDL_LOCATION = url;
        CNESSERVICE_EXCEPTION = e;
    }

    public CnesService() {
        super(__getWsdlLocation(), CNESSERVICE_QNAME);
    }

    public CnesService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CNESSERVICE_QNAME, features);
    }

    public CnesService(URL wsdlLocation) {
        super(wsdlLocation, CNESSERVICE_QNAME);
    }

    public CnesService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CNESSERVICE_QNAME, features);
    }

    public CnesService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CnesService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CnesServicePortType
     */
    @WebEndpoint(name = "CnesServicePort")
    public CnesServicePortType getCnesServicePort() {
        return super.getPort(new QName("http://servicos.saude.gov.br/cnes/v1r0/cnesservice", "CnesServicePort"), CnesServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CnesServicePortType
     */
    @WebEndpoint(name = "CnesServicePort")
    public CnesServicePortType getCnesServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://servicos.saude.gov.br/cnes/v1r0/cnesservice", "CnesServicePort"), CnesServicePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CNESSERVICE_EXCEPTION!= null) {
            throw CNESSERVICE_EXCEPTION;
        }
        return CNESSERVICE_WSDL_LOCATION;
    }

}
