
package br.gov.saude.servicos.cnes.v1r0.cnesservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CnesServicePortType", targetNamespace = "http://servicos.saude.gov.br/cnes/v1r0/cnesservice")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class,
    br.gov.saude.servicos.cnes.schema.cadsus.v5r0.cns.ObjectFactory.class,
    br.gov.saude.servicos.cnes.schema.cnes.v1r0.atividadeensino.ObjectFactory.class,
    br.gov.saude.servicos.cnes.schema.cnes.v1r0.cmpt.ObjectFactory.class,
    br.gov.saude.servicos.cnes.schema.cnes.v1r0.codigocnes.ObjectFactory.class,
    br.gov.saude.servicos.cnes.schema.cnes.v1r0.codigounidade.ObjectFactory.class,
    br.gov.saude.servicos.cnes.schema.cnes.v1r0.complementoesferaadministrativa.ObjectFactory.class,
    br.gov.saude.servicos.cnes.schema.cnes.v1r0.complementoestabelecimentosaude.ObjectFactory.class,
    br.gov.saude.servicos.cnes.schema.cnes.v1r0.complementoprofissionalsaude.ObjectFactory.class,
    br.gov.saude.servicos.cnes.schema.cnes.v1r0.dadosbasicosestabelecimento.ObjectFactory.class,
    br.gov.saude.servicos.cnes.schema.cnes.v1r0.dadoscomplementaresestabelecimentosaude.ObjectFactory.class,
    br.gov.saude.servicos.cnes.schema.cnes.v1r0.dadosgeraiscnes.ObjectFactory.class,
    br.gov.saude.servicos.cnes.schema.cnes.v1r0.dadosprincipaisestabelecimentosaude.ObjectFactory.class,
    br.gov.saude.servicos.cnes.schema.cnes.v1r0.diretor.ObjectFactory.class,
    br.gov.saude.servicos.cnes.schema.cnes.v1r0.equipamento.ObjectFactory.class,
    br.gov.saude.servicos.cnes.schema.cnes.v1r0.esferaadministrativa.ObjectFactory.class,
    br.gov.saude.servicos.cnes.schema.cnes.v1r0.grupohabilitacao.ObjectFactory.class,
    br.gov.saude.servicos.cnes.schema.cnes.v1r0.habilitacao.ObjectFactory.class,
    br.gov.saude.servicos.cnes.schema.cnes.v1r0.identificacaoestabelecimentosaude.ObjectFactory.class,
    br.gov.saude.servicos.cnes.schema.cnes.v1r0.leito.ObjectFactory.class,
    br.gov.saude.servicos.cnes.schema.cnes.v1r0.localizacao.ObjectFactory.class,
    br.gov.saude.servicos.cnes.schema.cnes.v1r0.samu.ObjectFactory.class,
    br.gov.saude.servicos.cnes.schema.cnes.v1r0.subgrupohabilitacao.ObjectFactory.class,
    br.gov.saude.servicos.cnes.schema.cnes.v1r0.subtipoestabelecimentosaude.ObjectFactory.class,
    br.gov.saude.servicos.cnes.schema.cnes.v1r0.tipoequipamento.ObjectFactory.class,
    br.gov.saude.servicos.cnes.schema.cnes.v1r0.tipoestabelecimentosaude.ObjectFactory.class,
    br.gov.saude.servicos.cnes.schema.cnes.v1r0.tipogestao.ObjectFactory.class,
    br.gov.saude.servicos.cnes.schema.cnes.v1r0.tipounidade.ObjectFactory.class,
    br.gov.saude.servicos.cnes.schema.cnes.v2r0.estabelecimentosaude.ObjectFactory.class,
    br.gov.saude.servicos.cnes.schema.corporativo.documento.v1r2.cpf.ObjectFactory.class,
    br.gov.saude.servicos.cnes.schema.corporativo.endereco.v1r1.bairro.ObjectFactory.class,
    br.gov.saude.servicos.cnes.schema.corporativo.endereco.v1r1.cep.ObjectFactory.class,
    br.gov.saude.servicos.cnes.schema.corporativo.endereco.v1r1.tipologradouro.ObjectFactory.class,
    br.gov.saude.servicos.cnes.schema.corporativo.endereco.v1r2.endereco.ObjectFactory.class,
    br.gov.saude.servicos.cnes.schema.corporativo.pessoafisica.v1r2.nomecompleto.ObjectFactory.class,
    br.gov.saude.servicos.cnes.schema.corporativo.pessoajuridica.v1r0.alvarasanitario.ObjectFactory.class,
    br.gov.saude.servicos.cnes.schema.corporativo.pessoajuridica.v1r0.cnae.ObjectFactory.class,
    br.gov.saude.servicos.cnes.schema.corporativo.pessoajuridica.v1r0.cnpj.ObjectFactory.class,
    br.gov.saude.servicos.cnes.schema.corporativo.pessoajuridica.v1r0.nomejuridico.ObjectFactory.class,
    br.gov.saude.servicos.cnes.schema.corporativo.telefone.v1r1.tipotelefone.ObjectFactory.class,
    br.gov.saude.servicos.cnes.schema.corporativo.telefone.v1r2.telefone.ObjectFactory.class,
    br.gov.saude.servicos.cnes.schema.corporativo.v1r1.uf.ObjectFactory.class,
    br.gov.saude.servicos.cnes.schema.corporativo.v1r2.email.ObjectFactory.class,
    br.gov.saude.servicos.cnes.schema.corporativo.v1r2.municipio.ObjectFactory.class,
    br.gov.saude.servicos.cnes.schema.corporativo.v1r2.pais.ObjectFactory.class,
    br.gov.saude.servicos.cnes.schema.profissionalsaude.v1r0.cbo.ObjectFactory.class,
    br.gov.saude.servicos.cnes.schema.profissionalsaude.v1r0.profissionalsaude.ObjectFactory.class,
    br.gov.saude.servicos.cnes.schema.profissionalsaude.v1r0.tipovinculoempregaticio.ObjectFactory.class,
    br.gov.saude.servicos.cnes.schema.profissionalsaude.v1r0.vinculoempregaticio.ObjectFactory.class,
    br.gov.saude.servicos.cnes.mensageria.falha.v5r0.mensagem.ObjectFactory.class,
    br.gov.saude.servicos.cnes.mensageria.falha.v5r0.msfalha.ObjectFactory.class,
    br.gov.saude.servicos.cnes.mensageria.v1r0.resultadopesquisacnesmunicipio.ObjectFactory.class,
    br.gov.saude.servicos.cnes.mensageria.v1r0.resultadopesquisadadoscomplementarescnes.ObjectFactory.class,
    br.gov.saude.servicos.cnes.mensageria.v1r0.resultadopesquisaestabelecimentosaude.ObjectFactory.class
})
public interface CnesServicePortType {


    /**
     * Consultar o Estabelecimento de Saude pelo c�digo do CNES.
     * 
     * @param requestConsultarEstabelecimentoSaude
     * @return
     *     returns ResponseConsultarEstabelecimentoSaude
     * @throws CnesFault
     */
    @WebMethod
    @WebResult(name = "responseConsultarEstabelecimentoSaude", targetNamespace = "http://servicos.saude.gov.br/cnes/v1r0/cnesservice", partName = "responseConsultarEstabelecimentoSaude")
    public ResponseConsultarEstabelecimentoSaude consultarEstabelecimentoSaude(
        @WebParam(name = "requestConsultarEstabelecimentoSaude", targetNamespace = "http://servicos.saude.gov.br/cnes/v1r0/cnesservice", partName = "requestConsultarEstabelecimentoSaude")
        RequestConsultarEstabelecimentoSaude requestConsultarEstabelecimentoSaude)
        throws CnesFault
    ;

    /**
     * Consultar o Estabelecimento de Saude pelo c�digo IBGE do Munic�pio.
     * 
     * @param requestConsultarEstabelecimentoSaudePorMunicipio
     * @return
     *     returns ResponseConsultarEstabelecimentoSaudePorMunicipio
     * @throws CnesFault
     */
    @WebMethod
    @WebResult(name = "responseConsultarEstabelecimentoSaudePorMunicipio", targetNamespace = "http://servicos.saude.gov.br/cnes/v1r0/cnesservice", partName = "responseConsultarEstabelecimentoSaudePorMunicipio")
    public ResponseConsultarEstabelecimentoSaudePorMunicipio consultarEstabelecimentoSaudePorMunicipio(
        @WebParam(name = "requestConsultarEstabelecimentoSaudePorMunicipio", targetNamespace = "http://servicos.saude.gov.br/cnes/v1r0/cnesservice", partName = "requestConsultarEstabelecimentoSaudePorMunicipio")
        RequestConsultarEstabelecimentoSaudePorMunicipio requestConsultarEstabelecimentoSaudePorMunicipio)
        throws CnesFault
    ;

    /**
     * Consultar os dados complementares do Estabelecimento de Saude.
     * 
     * @param requestConsultarDadosComplementaresEstabelecimentoSaude
     * @return
     *     returns ResponseConsultarDadosComplementaresEstabelecimentoSaude
     * @throws CnesFault
     */
    @WebMethod
    @WebResult(name = "responseConsultarDadosComplementaresEstabelecimentoSaude", targetNamespace = "http://servicos.saude.gov.br/cnes/v1r0/cnesservice", partName = "responseConsultarDadosComplementaresEstabelecimentoSaude")
    public ResponseConsultarDadosComplementaresEstabelecimentoSaude consultarDadosComplementaresEstabelecimentoSaude(
        @WebParam(name = "requestConsultarDadosComplementaresEstabelecimentoSaude", targetNamespace = "http://servicos.saude.gov.br/cnes/v1r0/cnesservice", partName = "requestConsultarDadosComplementaresEstabelecimentoSaude")
        RequestConsultarDadosComplementaresEstabelecimentoSaude requestConsultarDadosComplementaresEstabelecimentoSaude)
        throws CnesFault
    ;

}
