
package br.gov.saude.servicos.cnes.v1r0.estabelecimentosaudeservice;

import br.gov.saude.servicos.cnes.mensageria.v1r0.resultadoslocalizacaoestabelecimentosaude.ObjectFactory;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EstabelecimentoSaudeServicePortType", targetNamespace = "http://servicos.saude.gov.br/cnes/v1r0/estabelecimentosaudeservice")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    br.gov.saude.servicos.cnes.v1r0.estabelecimentosaudeservice.ObjectFactory.class,
    br.gov.saude.servicos.cnes.schema.cnes.v1r0.codigocnes.ObjectFactory.class,
    br.gov.saude.servicos.cnes.schema.cnes.v1r0.codigounidade.ObjectFactory.class,
    br.gov.saude.servicos.cnes.schema.cnes.v1r0.dadosgeraiscnes.ObjectFactory.class,
    br.gov.saude.servicos.cnes.schema.cnes.v1r0.dadosprecadastrocnes.ObjectFactory.class,
    br.gov.saude.servicos.cnes.schema.cnes.v1r0.diretor.ObjectFactory.class,
    br.gov.saude.servicos.cnes.schema.cnes.v1r0.esferaadministrativa.ObjectFactory.class,
    br.gov.saude.servicos.cnes.schema.cnes.v1r0.localizacao.ObjectFactory.class,
    br.gov.saude.servicos.cnes.schema.cnes.v1r0.servicoclassificacao.ObjectFactory.class,
    br.gov.saude.servicos.cnes.schema.cnes.v1r0.servicoclassificacoes.ObjectFactory.class,
    br.gov.saude.servicos.cnes.schema.cnes.v1r0.servicoespecializado.ObjectFactory.class,
    br.gov.saude.servicos.cnes.schema.cnes.v1r0.servicoespecializados.ObjectFactory.class,
    br.gov.saude.servicos.cnes.schema.cnes.v1r0.tipounidade.ObjectFactory.class,
    br.gov.saude.servicos.cnes.schema.corporativo.documento.v1r2.cpf.ObjectFactory.class,
    br.gov.saude.servicos.cnes.schema.corporativo.endereco.v1r1.bairro.ObjectFactory.class,
    br.gov.saude.servicos.cnes.schema.corporativo.endereco.v1r1.cep.ObjectFactory.class,
    br.gov.saude.servicos.cnes.schema.corporativo.endereco.v1r1.tipologradouro.ObjectFactory.class,
    br.gov.saude.servicos.cnes.schema.corporativo.endereco.v1r2.endereco.ObjectFactory.class,
    br.gov.saude.servicos.cnes.schema.corporativo.pessoafisica.v1r2.nomecompleto.ObjectFactory.class,
    br.gov.saude.servicos.cnes.schema.corporativo.pessoajuridica.v1r0.cnpj.ObjectFactory.class,
    br.gov.saude.servicos.cnes.schema.corporativo.pessoajuridica.v1r0.naturezajuridica.ObjectFactory.class,
    br.gov.saude.servicos.cnes.schema.corporativo.pessoajuridica.v1r0.nomejuridico.ObjectFactory.class,
    br.gov.saude.servicos.cnes.schema.corporativo.pessoajuridica.v1r0.tiponaturezajuridica.ObjectFactory.class,
    br.gov.saude.servicos.cnes.schema.corporativo.telefone.v1r1.tipotelefone.ObjectFactory.class,
    br.gov.saude.servicos.cnes.schema.corporativo.telefone.v1r2.telefone.ObjectFactory.class,
    br.gov.saude.servicos.cnes.schema.corporativo.v1r1.uf.ObjectFactory.class,
    br.gov.saude.servicos.cnes.schema.corporativo.v1r2.email.ObjectFactory.class,
    br.gov.saude.servicos.cnes.schema.corporativo.v1r2.municipio.ObjectFactory.class,
    br.gov.saude.servicos.cnes.schema.corporativo.v1r2.pais.ObjectFactory.class,
    br.gov.saude.servicos.cnes.mensageria.falha.v5r0.mensagem.ObjectFactory.class,
    br.gov.saude.servicos.cnes.mensageria.falha.v5r0.msfalha.ObjectFactory.class,
    br.gov.saude.servicos.cnes.mensageria.v1r0.filtrolocalizacaoestabelecimentosaude.ObjectFactory.class,
    br.gov.saude.servicos.cnes.mensageria.v1r0.filtropesquisaestabelecimentosaude.ObjectFactory.class,
    br.gov.saude.servicos.cnes.mensageria.v1r0.filtropesquisaprecadastrocnes.ObjectFactory.class,
    br.gov.saude.servicos.cnes.mensageria.v1r0.paginacao.ObjectFactory.class,
    br.gov.saude.servicos.cnes.mensageria.v1r0.resultadolocalizacaoestabelecimentosaude.ObjectFactory.class,
    ObjectFactory.class
})
public interface EstabelecimentoSaudeServicePortType {


    /**
     * Consultar os dados b�sicos do Estabelecimento de Saude pelo c�digo do CNES.
     * 
     * @param requestConsultarEstabelecimentoSaude
     * @return
     *     returns ResponseConsultarEstabelecimentoSaude
     * @throws EstabelecimentoSaudeFault
     */
    @WebMethod
    @WebResult(name = "responseConsultarEstabelecimentoSaude", targetNamespace = "http://servicos.saude.gov.br/cnes/v1r0/estabelecimentosaudeservice", partName = "responseConsultarEstabelecimentoSaude")
    public ResponseConsultarEstabelecimentoSaude consultarEstabelecimentoSaude(
        @WebParam(name = "requestConsultarEstabelecimentoSaude", targetNamespace = "http://servicos.saude.gov.br/cnes/v1r0/estabelecimentosaudeservice", partName = "requestConsultarEstabelecimentoSaude")
        RequestConsultarEstabelecimentoSaude requestConsultarEstabelecimentoSaude)
        throws EstabelecimentoSaudeFault
    ;

    /**
     * Localiza os Estabelecimentos de Saude pelas coordenadas.
     * 
     * @param requestLocalizarEstabelecimentoSaude
     * @return
     *     returns ResponseLocalizarEstabelecimentoSaude
     * @throws EstabelecimentoSaudeFault
     */
    @WebMethod
    @WebResult(name = "responseLocalizarEstabelecimentoSaude", targetNamespace = "http://servicos.saude.gov.br/cnes/v1r0/estabelecimentosaudeservice", partName = "responseLocalizarEstabelecimentoSaude")
    public ResponseLocalizarEstabelecimentoSaude localizarEstabelecimentoSaude(
        @WebParam(name = "requestLocalizarEstabelecimentoSaude", targetNamespace = "http://servicos.saude.gov.br/cnes/v1r0/estabelecimentosaudeservice", partName = "requestLocalizarEstabelecimentoSaude")
        RequestLocalizarEstabelecimentoSaude requestLocalizarEstabelecimentoSaude)
        throws EstabelecimentoSaudeFault
    ;

    /**
     * Consultar os dados b�sicos do precadastro do Estabelecimento de Saude pelo c�digo do CNES.
     * 
     * @param requestConsultarPrecadastroCNES
     * @return
     *     returns ResponseConsultarPrecadastroCNES
     * @throws EstabelecimentoSaudeFault
     */
    @WebMethod
    @WebResult(name = "responseConsultarPrecadastroCNES", targetNamespace = "http://servicos.saude.gov.br/cnes/v1r0/estabelecimentosaudeservice", partName = "responseConsultarPrecadastroCNES")
    public ResponseConsultarPrecadastroCNES consultarPrecadastroCNES(
        @WebParam(name = "requestConsultarPrecadastroCNES", targetNamespace = "http://servicos.saude.gov.br/cnes/v1r0/estabelecimentosaudeservice", partName = "requestConsultarPrecadastroCNES")
        RequestConsultarPrecadastroCNES requestConsultarPrecadastroCNES)
        throws EstabelecimentoSaudeFault
    ;

}
