
package br.gov.saude.servicos.cnes.v1r0.estabelecimentosaudeservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "EstabelecimentoSaudeService", targetNamespace = "http://servicos.saude.gov.br/cnes/v1r0/estabelecimentosaudeservice", wsdlLocation = "https://servicos.saude.gov.br/cnes/EstabelecimentoSaudeService/v1r0?wsdl")
public class EstabelecimentoSaudeService
    extends Service
{

    private final static URL ESTABELECIMENTOSAUDESERVICE_WSDL_LOCATION;
    private final static WebServiceException ESTABELECIMENTOSAUDESERVICE_EXCEPTION;
    private final static QName ESTABELECIMENTOSAUDESERVICE_QNAME = new QName("http://servicos.saude.gov.br/cnes/v1r0/estabelecimentosaudeservice", "EstabelecimentoSaudeService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://servicos.saude.gov.br/cnes/EstabelecimentoSaudeService/v1r0?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ESTABELECIMENTOSAUDESERVICE_WSDL_LOCATION = url;
        ESTABELECIMENTOSAUDESERVICE_EXCEPTION = e;
    }

    public EstabelecimentoSaudeService() {
        super(__getWsdlLocation(), ESTABELECIMENTOSAUDESERVICE_QNAME);
    }

    public EstabelecimentoSaudeService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ESTABELECIMENTOSAUDESERVICE_QNAME, features);
    }

    public EstabelecimentoSaudeService(URL wsdlLocation) {
        super(wsdlLocation, ESTABELECIMENTOSAUDESERVICE_QNAME);
    }

    public EstabelecimentoSaudeService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ESTABELECIMENTOSAUDESERVICE_QNAME, features);
    }

    public EstabelecimentoSaudeService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EstabelecimentoSaudeService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EstabelecimentoSaudeServicePortType
     */
    @WebEndpoint(name = "EstabelecimentoSaudeServicePort")
    public EstabelecimentoSaudeServicePortType getEstabelecimentoSaudeServicePort() {
        return super.getPort(new QName("http://servicos.saude.gov.br/cnes/v1r0/estabelecimentosaudeservice", "EstabelecimentoSaudeServicePort"), EstabelecimentoSaudeServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EstabelecimentoSaudeServicePortType
     */
    @WebEndpoint(name = "EstabelecimentoSaudeServicePort")
    public EstabelecimentoSaudeServicePortType getEstabelecimentoSaudeServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://servicos.saude.gov.br/cnes/v1r0/estabelecimentosaudeservice", "EstabelecimentoSaudeServicePort"), EstabelecimentoSaudeServicePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ESTABELECIMENTOSAUDESERVICE_EXCEPTION!= null) {
            throw ESTABELECIMENTOSAUDESERVICE_EXCEPTION;
        }
        return ESTABELECIMENTOSAUDESERVICE_WSDL_LOCATION;
    }

}
